#!/bin/bash

set -euo pipefail

rm ./config/* 2>/dev/null || true

mkdir -p ./config/

vagrant destroy -f || true
vagrant destroy -f || true

echo "Waiting for VMs to be down..."
sleep 10

rm -rf ./.vagrant
rm -rf ./vagrant-shared/

[ -f .vagrant-state ] && rm .vagrant-state
[ -f .vagrant-env ] && rm .vagrant-env
